#%RAML 0.8
---
title: Simple API
version: v1

/songs:
  description: Collection of available songs
  get:
    description: Get a list of songs
    responses:
      200:
        body:
          application/json:
            example: |
                [
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440000",
                    "songTitle": "Get Lucky"
                  },
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440111",
                    "songTitle": "Loose yourself to dance"
                  },
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440222",
                    "songTitle": "Gio sorgio by Moroder"
                  }
                ]
  /{songId}:
    description: Song entity
    get:
  post:
/artists:
  description: Collection of artists
  get:
    description: Get the artists list
  /{artistId}:
    get:
    /albums:
      get:
